Personal_Blog/Personal_Blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(
        'admin/',
        admin.site.urls
        ),
    re_path(
        '',
        include('apps.home.urls')
        ),
    re_path(
        '',
        include('apps.authors.urls')
        ),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Personal_Blog/apps/authors/urls.py
from django.urls import path, re_path, include
from . import views

app_name = "author_urls"

urlpatterns = [
    path(
        'Blog/<pk>',
        views.blog_DetailView.as_view(),
        name="base_Blog"
        ),
    path(
        'listar_Blogs/',
        views.Blog_ListView.as_view(),
        name="list_Blog"
        ),
    
]

Personal_Blog/apps/home/urls.py
from django.urls import path
from . import views

app_name = "home_urls"

urlpatterns = [
    path(
        '',
        views.Home_templateView.as_view(),
        name="home"),
    path(
        'contacto/',
        views.Contact_templateView.as_view(),
        name="contact"),
    path(
        'Acerca_de_nosotros/',
        views.About_templateView.as_view(),
        name="About_us"),
    path(
        'Exito/',
        views.Success_TemplateView.as_view(),
        name="success"),
    
]

Personal_Blog/apps/authors/models.py
from django.db import models

#third apps
from ckeditor.fields import RichTextField

class Author(models.Model):
    """Model definition for Author."""
    name = models.CharField(('Nombres'), max_length=75)
    last_name = models.CharField(('Apellidos'), max_length=75)
    avatar = models.CharField(('Avatar'), max_length=50)
    description = models.CharField('Descripción', max_length=250)

    class Meta:
        verbose_name = 'Autor'
        verbose_name_plural = 'Autores'

    def __str__(self):
        return "{}".format(self.avatar)

class Post(models.Model):
    title = models.CharField(("titulo"), max_length=150)
    post_date = models.DateField("Fecha de creacion", auto_now=False, auto_now_add=True)
    content = RichTextField()
    Reference_image = models.ImageField("Imagen de referencia", upload_to='media/refernce')
    post_status = models.BooleanField(default=False)
    name = models.ForeignKey(Author, on_delete=models.CASCADE)
    

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return "{} {} {} ".format(self.id, self.title, self.post_status)

Personal_Blog/apps/home/models.py
from django.db import models

# Create your models here.

Personal_Blog/apps/home/forms.py
from django import forms

class Contact_Form(forms.Form):
    email = forms.EmailField(required=True)
    subject = forms.CharField(max_length=30, required=False)
    message = forms.CharField(max_length=255, required=True)

Personal_Blog/apps/authors/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
#our apps
from .models import Post


class blog_DetailView(DetailView):
    template_name = "blog/base_blog.html"
    model = Post
    context_object_name = "posts"

    def get_context_data(self, **kwargs):
        context = super(blog_DetailView, self).get_context_data(**kwargs)
        posts = Post.objects.get(id = self.kwargs['pk'])
        return context


class blog_TemplateView(TemplateView):
    template_name = "blog/base_blog.html"


class Blog_ListView(ListView):
    model = Post
    template_name = "blog/list_blogs.html"
    context_object_name = "List"
    paginate_by = 4

Personal_Blog/apps/home/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.urls import reverse

from .forms import Contact_Form


from django.views.generic import (
    TemplateView,
    DetailView,
    ListView
    )


class Home_templateView(TemplateView):
    template_name = "home/home.html"


class Contact_templateView(FormView):
    template_name = "home/contact.html"
    form_class = Contact_Form
    success_url = 'home/success.html'

    def form_valid(self, form):
        from_email = form.cleaned_data['email']
        message = form.cleaned_data['message'] + "Mensaje enviado de:" + " " + from_email 
        subject = form.cleaned_data['subject']  

        try:
            send_mail(subject, message, "zapeta.pablo@gmail.com", ["pablozapetalop@gmail.com"])
        except BadHeaderError:
            return HttpResponse('Header Invalido encontrado!!.')
        return HttpResponseRedirect(
            reverse(
                'home_urls:success'
            )
        )


class About_templateView(TemplateView):
    template_name = "home/about.html"



class Success_TemplateView(TemplateView):
    template_name = "home/success.html"

Personal_Blog/templates/blog/base_blog.html
{% extends 'includes/base.html' %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 center-align">
                <h1>{{posts.title}}</h1>
            </div>
            <div class="col s12 m2 push-m4">
                <div class="card">
                <div class="card-image">
                    <img src="{{posts.Reference_image.url}}" style="width: auto; height: auto;">
                </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col s6 m6 push-m1">
                {{posts.content|safe}}
                {{posts.content}}
            </div>
        </div>
    </div>
        {% include 'includes/footer.html' %}
{% endblock content %}
    

Personal_Blog/templates/blog/list_blogs.html
{% extends 'includes/base.html' %}
{% load static %}
{% block title %}
    Blogs
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}
<!-- <div style="background-image: url(/static/images/python.jpg);"> -->
    <!-- <div class="parallax-container"> -->
        <!-- <div class="section no-pad-bot"> -->
            <div class="container">
                <div class="row">
                    {% for li in List %}
                        {% if forloop.counter|divisibleby:2 %}
                            <div class="col s12 m6">
                                <div class="card red darken-4">
                                    <div class="card-image waves-effect waves-block waves-light">
                                        <img class="activator" src="{{li.Reference_image.url}}" alt="Imagen" style="width: 31em; height: 20em;">
                                    </div>
                                        <a class="btn-floating halfway-fab waves-effect waves-light red" href="{% url 'author_urls:base_Blog' li.id %}">
                                            <i class="material-icons">chrome_reader_mode</i>
                                        </a>
                                    <div class="card-content">
                                        <span class="card-title activator white-text">{{li.title}} {{li.id}}<i class="material-icons right">more_vert</i></span>
                                </div>
                                <div class="card-reveal grey darken-4 white-text">
                                    <span class="card-title white-text">Escrito por: {{li.name}}<i class="material-icons right">close</i></span>
                                    <p>{{ li.content|safe|slice:":100" }}</p>
                                </div>
                                </div>
                            </div>
                            <!-- <div class="col s12 m4">
                                <div class="card">
                                    <h1>CENTRO</h1>
                                </div>
                            </div>  -->
                            {% else %}
                            <div class="col s12 m6">
                                <div class="card red darken-4 pull-m2">
                                    <div class="card-image waves-effect waves-block waves-light">
                                        <img class="activator" src="{{li.Reference_image.url}}" alt="Imagen" style="width: 31em; height: 20em;">
                                    </div>
                                        <a class="btn-floating halfway-fab waves-effect waves-light red" href="{% url 'author_urls:base_Blog' li.id %}">
                                            <i class="material-icons">chrome_reader_mode</i>
                                        </a>
                                    <div class="card-content">
                                        <span class="card-title activator white-text">{{li.title}} {{li.id}}<i class="material-icons right">more_vert</i></span>
                                </div>
                                <div class="card-reveal grey darken-4 white-text">
                                    <span class="card-title white-text">Escrito por: {{li.name}}<i class="material-icons right">close</i></span>
                                    <p>{{ li.content|safe|slice:":100" }}</p>
                                </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        <!-- </div> -->
        <!-- <div class="parallax"><img src="{% static 'images/python.jpg' %}" alt="Unsplashed background img 1"></div> -->
    <!-- </div> -->
<!-- </div> -->

<div class="container">
    <!-- <div class="section no-pad-bot"></div> -->
        {% if is_paginated %}
                <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="activate deep-orange darken-3"><a href="?page={{page_obj.previous_page_number}}"><i class="material-icons white-text">chevron_left</i></a></li>
                {% endif %}

                {% for page in paginator.page_range %}
                    {% ifequal page page_obj.number %}
                    <h4 class="truncate">Pagina {{page}}</h4>
                    {% else %}
                        <li class="active deep-orange activate deep-orange darken-3"><a href="?page={{page}}" aria-label="Page">{{page}}</a></li>
                    {% endifequal %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li class="activate deep-orange darken-3"><a href="?page={{page_obj.next_page_number}}"><i class="material-icons white-text">chevron_right</i></a></li>
                {% endif %}
                </ul>
        {% endif %}
    <!-- </div> -->
<!-- <div class="parallax"><img src="{% static 'images/python.jpg' %}" alt="Unsplashed background img 1"></div> -->
</div>
<!-- 
<div class="container">
    <ul class="pagination">
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
        <li class="active"><a href="#!">1</a></li>
        <li class="waves-effect"><a href="#!">2</a></li>
        <li class="waves-effect"><a href="#!">3</a></li>
        <li class="waves-effect"><a href="#!">4</a></li>
        <li class="waves-effect"><a href="#!">5</a></li>
        <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
      </ul>
</div> -->
{% include 'includes/footer.html' %}
{% endblock content %}
    

Personal_Blog/templates/home/about.html
{% extends 'includes/base.html' %}


{% block content %}
{% include 'includes/header.html' %}
<h1 class="red-text lighten-2">ACERCA DE NOSOTROS</h1>
{% include 'includes/footer.html' %}
{% endblock content %}
    

Personal_Blog/templates/home/contact.html
{% extends 'includes/base.html' %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="container">
        <form method="POST"> {% csrf_token %}
            {{ form.as_p }}
            <div class="form-actions">
                <button type="submit">Send</button>
            </div>
        </form>
    </div>
    
    {% include 'includes/footer.html' %}
{% endblock content %}

    

Personal_Blog/templates/home/home.html
{% extends 'includes/base.html' %}
{% load static %}


{% block content %}
  {% include 'includes/header.html' %}


  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center red-text text-darken-4">BIENVENIDOS</h1>
        <div class="row center">
          <h5 class="header col s12 light">Blog de Switcher enfocado al desarrollo web en django </h5>
        </div>
        <div class="row center">
          <a href="{% url 'author_urls:base_Blog' 1 %}" id="download-button" class="btn-large waves-effect waves-light red darken-1">BLOG</a>
        </div>
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="{% static 'images/background1.png' %}" alt="Unsplashed background img 1"></div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Speeds up development</h5>

            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">group</i></h2>
            <h5 class="center">User Experience Focused</h5>

            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>

    </div>
  </div>

{% include 'includes/footer.html' %}

{% endblock content %}
    

Personal_Blog/templates/home/success.html
{% extends 'includes/base.html' %}


{% block title %} Correcto {% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <h1>EXITO</h1>
    {% include 'includes/footer.html' %}
{% endblock content %}
    
    

Personal_Blog/templates/includes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>{% block title %} {% endblock title %} </title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
  
  {% block content %} {% endblock content %}

  <!--  Scripts-->
  <script src="{% static 'jquery/jquery.min.js' %}"></script>
  <script src="{% static 'js/materialize.js' %}"></script>
  <script src="{% static 'js/init.js' %}"></script>

  </body>
</html>

Personal_Blog/templates/includes/footer.html
 
  <footer class="page-footer red darken-4">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>

Personal_Blog/templates/includes/header.html
<nav class="grey darken-4" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="{% url 'home_urls:home' %}" class="brand-logo orange-text darken-4">Logo</a>
      <ul class="right hide-on-med-and-down">
        <li><a class="orange-text darken-4" href="{% url 'author_urls:list_Blog' %}">Lista Blogs</a></li>
        <li><a class="orange-text darken-4" href="{% url 'home_urls:contact' %}">Contacto</a></li>
        <li><a class="orange-text darken-4" href="{% url 'home_urls:About_us' %}">Acerca de nosotros</a></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="{% url 'author_urls:base_Blog' 1 %}">Barra de navegacion</a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>